const fs = require('fs');
const path = require('path');

const NAMESPACE = 'Game_DataLoader';

function toPascal(name) {
    const s = String(name || '');
    if (s.length === 0) {
        return s;
    }
    return s.charAt(0).toUpperCase() + s.slice(1);
}

// enum 네이밍 컨벤션 강제: E접두사 제거 + 'Type' 접미사 필수 (예: EStatType -> StatType, ECurrency -> CurrencyType)
function normalizeEnumName(name) {
    let n = String(name || '').trim();
    if (/^E[A-Z]/.test(n)) {
        n = n.slice(1);
    }
    if (!n.endsWith('Type')) {
        n += 'Type';
    }
    return n;
}

// enum 정의 파일(_Enum 등)에서 수집한 enum 이름 목록. 타입행에 enum명만 적으면 enum으로 인식한다.
let knownEnums = new Set();

function setKnownEnums(names) {
    knownEnums = new Set(names || []);
}

function csType(type) {
    let t = String(type || 'string').trim();
    if (t.endsWith('!')) {
        t = t.slice(0, -1);
    }
    const lower = t.toLowerCase();
    if (lower.startsWith('enum:')) {
        const raw = t.slice('enum:'.length).trim();
        const normalized = normalizeEnumName(raw);
        console.log(`[WARN] 'enum:' 접두 표기는 폐기되었습니다: '${type}' -> 엑셀 자료형을 '${normalized}'로만 적으세요.`);
        return 'Game.GameEnum.' + normalized;
    }
    // 접두사 없는 enum 표기: 타입행 값이 enum 정의(_Enum)에 있으면 enum으로 취급
    if (knownEnums.has(t)) {
        return 'Game.GameEnum.' + t;
    }
    if (/^E?[A-Z]/.test(t) && knownEnums.has(normalizeEnumName(t))) {
        const normalized = normalizeEnumName(t);
        console.log(`[WARN] enum 이름 컨벤션 위반: '${t}' -> '${normalized}' 로 정규화됨. 엑셀 자료형 표기를 '${normalized}'로 수정하세요.`);
        return 'Game.GameEnum.' + normalized;
    }
    switch (lower) {
        case 'intarray':
            return 'int[]';
        case 'floatarray':
            return 'float[]';
        case 'stringarray':
            return 'string[]';
        case 'stringarray|':
            return 'string[]';
        case 'int':
        case 'integer':
            return 'int';
        case 'long':
            return 'long';
        case 'float':
            return 'float';
        case 'double':
            return 'double';
        case 'number':
            return 'float';
        case 'bool':
        case 'boolean':
            return 'bool';
        case 'string':
        case 'text':
            return 'string';
        default:
            if (/^[A-Z]/.test(t)) {
                console.log(`[WARN] 알 수 없는 자료형 '${t}': enum이라면 _Enum 정의에 추가하세요. string으로 처리합니다.`);
            }
            return 'string';
    }
}

function findKeyColumn(columns) {
    for (const c of columns) {
        if (String(c.name).toLowerCase() === 'id') {
            return c;
        }
    }
    return columns.length > 0 ? columns[0] : null;
}

// Code(문자열 논리 식별자) 컬럼 보유 여부 — 있으면 CodeContainer를 찍어 Code 조회를 지원한다
function hasCodeColumn(columns) {
    for (const c of columns) {
        if (String(c.name).toLowerCase() === 'code') {
            return true;
        }
    }
    return false;
}

function buildTableClass(sheetName, columns) {
    const key = findKeyColumn(columns);
    const keyType = key ? csType(key.type) : 'int';
    const keyProp = key ? toPascal(key.name) : 'Id';
    const interfaces = [`IDataKey<${keyType}>`, 'IData'];

    const lines = [];
    lines.push('// <auto-generated />');
    lines.push('using Newtonsoft.Json;');
    lines.push('');
    lines.push(`namespace ${NAMESPACE}`);
    lines.push('{');
    lines.push(`    public partial class ${sheetName} : ${interfaces.join(', ')}`);
    lines.push('    {');
    for (const c of columns) {
        lines.push(`        [JsonProperty("${c.name}")] public ${csType(c.type)} ${toPascal(c.name)} { get; private set; }`);
    }
    lines.push('');
    lines.push(`        [JsonIgnore] public ${keyType} Key => ${keyProp};`);
    lines.push('    }');
    lines.push('}');
    return lines.join('\n') + '\n';
}

function buildContainerEntry(sheetName, keyType, hasCode) {
    const lines = [];
    lines.push(`    public abstract class ${sheetName}DictionaryContainer`);
    lines.push(`        : DictionaryContainer<${keyType}, ${sheetName}>`);
    lines.push('    {');
    lines.push(`        public override string Name => "${sheetName}";`);
    lines.push('    }');
    lines.push('');
    lines.push(`    public abstract class ${sheetName}DictionaryGroupContainer`);
    lines.push(`        : DictionaryGroupContainer<${keyType}, ${sheetName}>`);
    lines.push('    {');
    lines.push(`        public override string Name => "${sheetName}";`);
    lines.push('    }');
    // Code 컬럼이 있으면 Code 조회 변형도 제공한다 (Get("battlecruiser") / GetGroup).
    // 프레임워크 특례가 아니라 SubCollection 훅을 쓴 '생성된 사용례'다 —
    // Id 외 다른 컬럼으로 캐싱이 필요하면 콘크리트 컨테이너에서 똑같이 오버라이드하면 된다.
    if (hasCode && keyType === 'int') {
        lines.push('');
        lines.push(`    public abstract class ${sheetName}CodeContainer`);
        lines.push(`        : DictionaryContainer<${keyType}, ${sheetName}>`);
        lines.push('    {');
        lines.push(`        public override string Name => "${sheetName}";`);
        lines.push('');
        lines.push('        /// <summary>Code로 단건 조회. Code가 중복되면 첫 행을 돌려준다.</summary>');
        lines.push(`        public ${sheetName} Get(string code)`);
        lines.push('        {');
        lines.push('            IReadOnlyList<' + sheetName + '> list = GetGroup(code);');
        lines.push('            return list != null && list.Count > 0 ? list[0] : null;');
        lines.push('        }');
        lines.push('');
        lines.push('        /// <summary>Code가 같은 행 묶음. 없으면 null.</summary>');
        lines.push(`        public IReadOnlyList<${sheetName}> GetGroup(string code)`);
        lines.push('        {');
        lines.push('            if (string.IsNullOrEmpty(code))');
        lines.push('            {');
        lines.push('                return null;');
        lines.push('            }');
        lines.push(`            _dicByCode.TryGetValue(code, out List<${sheetName}> list);`);
        lines.push('            return list;');
        lines.push('        }');
        lines.push('');
        lines.push(`        public bool TryGet(string code, out ${sheetName} value)`);
        lines.push('        {');
        lines.push('            value = Get(code);');
        lines.push('            return value != null;');
        lines.push('        }');
        lines.push('');
        lines.push('        public bool ContainsCode(string code)');
        lines.push('        {');
        lines.push('            return string.IsNullOrEmpty(code) == false && _dicByCode.ContainsKey(code);');
        lines.push('        }');
        lines.push('');
        lines.push(`        protected Dictionary<string, List<${sheetName}>> _dicByCode;`);
        lines.push('');
        lines.push('        protected override void SubCollectionConstructor(int count)');
        lines.push('        {');
        lines.push('            base.SubCollectionConstructor(count);');
        lines.push('');
        lines.push(`            _dicByCode = new Dictionary<string, List<${sheetName}>>(count);`);
        lines.push('        }');
        lines.push('');
        lines.push(`        protected override void SubCollectionAdd(${keyType} key, ${sheetName} tValue)`);
        lines.push('        {');
        lines.push('            base.SubCollectionAdd(key, tValue);');
        lines.push('');
        lines.push('            if (string.IsNullOrEmpty(tValue.Code))');
        lines.push('            {');
        lines.push('                return;');
        lines.push('            }');
        lines.push('');
        lines.push(`            if (_dicByCode.TryGetValue(tValue.Code, out List<${sheetName}> list) == false)`);
        lines.push('            {');
        lines.push(`                list = new List<${sheetName}>(1);`);
        lines.push('                _dicByCode.Add(tValue.Code, list);');
        lines.push('            }');
        lines.push('');
        lines.push('            list.Add(tValue);');
        lines.push('        }');
        lines.push('    }');
    }
    return lines.join('\n');
}

// 기존 Containers.Generated.cs에서 {시트명: {keyType, hasCode}} 엔트리 복원 (부분 export 시 다른 테이블 유지용)
function parseExistingContainerEntries(filePath) {
    const entries = {};
    if (!fs.existsSync(filePath)) {
        return entries;
    }
    const text = fs.readFileSync(filePath, 'utf8');
    const re = /:\s*DictionaryContainer<([^,>]+),\s*(\w+)>/g;
    let m;
    while ((m = re.exec(text)) !== null) {
        entries[m[2]] = { keyType: m[1].trim(), hasCode: false };
    }
    const reCode = /public\s+abstract\s+class\s+(\w+)CodeContainer\b/g;
    while ((m = reCode.exec(text)) !== null) {
        if (entries[m[1]]) {
            entries[m[1]].hasCode = true;
        }
    }
    return entries;
}

const CONTAINERS_FILE = 'Containers.Generated.cs';

/**
 * 추상 컨테이너 베이스를 Containers.Generated.cs 한 파일에 모아서 생성한다.
 * - 테이블마다 DictionaryContainer / DictionaryGroupContainer 변형을 선언
 *   (Code 컬럼이 있는 int 키 테이블은 CodeContainer 변형도 추가)
 * - 콘크리트 XxxDataContainer는 클라이언트가 직접 만들어 둘 중 하나를 상속한다
 * - 기존 파일과 병합하므로 부분 export(file/modified)에도 안전하다
 */
function generateContainersFile(csOutputPath, schemas) {
    if (!csOutputPath || !schemas) {
        return false;
    }
    if (!fs.existsSync(csOutputPath)) {
        fs.mkdirSync(csOutputPath, { recursive: true });
    }

    const filePath = path.join(csOutputPath, CONTAINERS_FILE);
    const entries = parseExistingContainerEntries(filePath);

    let updated = 0;
    for (const [sheetName, columns] of Object.entries(schemas)) {
        if (!columns || columns.length === 0) {
            continue;
        }
        const key = findKeyColumn(columns);
        entries[sheetName] = {
            keyType: key ? csType(key.type) : 'int',
            hasCode: hasCodeColumn(columns)
        };
        updated++;
    }
    if (updated === 0) {
        return false;
    }

    const names = Object.keys(entries).sort();
    const blocks = names.map(name => buildContainerEntry(name, entries[name].keyType, entries[name].hasCode));

    const header = [
        '// <auto-generated />',
        '// smart_exporter(class_generator)로 자동 생성된 파일입니다. 수동 편집 금지.',
        '',
        'using System.Collections.Generic;',
        '',
        `namespace ${NAMESPACE}`,
        '{'
    ].join('\n');

    fs.writeFileSync(filePath, header + '\n' + blocks.join('\n\n') + '\n}\n', 'utf8');
    return true;
}

// DataLoader/Containers에서 콘크리트 컨테이너 클래스명 수집
// (public class Xxx : YyyCodeContainer / YyyDictionaryContainer / YyyDictionaryGroupContainer, abstract 제외)
function collectConcreteContainers(containersPath) {
    if (!containersPath || !fs.existsSync(containersPath)) {
        return [];
    }
    const names = new Set();
    const files = fs.readdirSync(containersPath).filter(f => f.endsWith('.cs'));
    for (const file of files) {
        const text = fs.readFileSync(path.join(containersPath, file), 'utf8');
        const re = /public\s+(?:sealed\s+)?class\s+(\w+)\s*:\s*\w*(?:CodeContainer|DictionaryContainer|DictionaryGroupContainer)\b/g;
        let m;
        while ((m = re.exec(text)) !== null) {
            names.add(m[1]);
        }
    }
    return [...names].sort();
}

/**
 * GameRoot partial(컨테이너 접근 프로퍼티)을 GameRoot.Generated.cs에 생성한다.
 * - DataLoader/Containers의 콘크리트 컨테이너를 스캔해 GameRoot.Instance.XxxDataContainer로 노출
 * - 내용이 기존 파일과 같으면 다시 쓰지 않는다 (Unity 불필요 재임포트 방지)
 * - 반환: { count, written } / 스캔 결과가 0개인데 기존 파일이 있으면 안전을 위해 건너뛰고 null 반환
 */
function generateGameRootFile(containersPath, gameRootOutputPath) {
    if (!containersPath || !gameRootOutputPath) {
        return null;
    }

    const names = collectConcreteContainers(containersPath);
    if (names.length === 0 && fs.existsSync(gameRootOutputPath)) {
        console.log(`[WARN] 콘크리트 컨테이너를 찾지 못해 GameRoot 생성을 건너뜁니다. 경로 확인: ${containersPath}`);
        return null;
    }

    const lines = [
        '// <auto-generated />',
        '// smart_exporter(class_generator)로 자동 생성된 파일입니다. 수동 편집 금지.',
        '// 콘크리트 컨테이너(DataLoader/Containers) 추가/삭제 후 run_win.bat을 다시 돌리면 갱신된다.',
        '',
        `using ${NAMESPACE};`,
        '',
        'namespace Game_Core',
        '{',
        '    public partial class GameRoot',
        '    {'
    ];
    for (const name of names) {
        lines.push(`        public ${name} ${name} => DataManager.Instance.GetContainer<${name}>();`);
    }
    lines.push('    }');
    lines.push('}');
    const content = lines.join('\n') + '\n';

    if (fs.existsSync(gameRootOutputPath) && fs.readFileSync(gameRootOutputPath, 'utf8') === content) {
        return { count: names.length, written: false };
    }

    const dir = path.dirname(gameRootOutputPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(gameRootOutputPath, content, 'utf8');
    return { count: names.length, written: true };
}

function generateDataClass(sheetName, columns, csOutputPath) {
    if (!csOutputPath || !columns || columns.length === 0) {
        return false;
    }
    if (!fs.existsSync(csOutputPath)) {
        fs.mkdirSync(csOutputPath, { recursive: true });
    }
    fs.writeFileSync(path.join(csOutputPath, `${sheetName}.cs`), buildTableClass(sheetName, columns), 'utf8');
    return true;
}

module.exports = { generateDataClass, generateContainersFile, generateGameRootFile, csType, toPascal, normalizeEnumName, setKnownEnums };
