using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Game_DataLoader
{
    public static class DbGenerator
    {
        public const string ContainersFileName = "Containers.Generated.cs";
        public const string Namespace = "Game_DataLoader";
        public const string EnumNamespace = "Game";
        public const string EnumWrapper = "GameEnum";

        private const string AutoHeader =
            "// <auto-generated />\n" +
            "// Tools > GameData > DB Generate 로 생성된 파일입니다. 수동 편집 금지.\n";

        /// <summary>
        /// 원본 → JSON + 스키마 → C# 을 한 번에.
        /// 두 단계가 같은 DataIssueLog 를 쓰므로 어느 쪽에서 깨졌든 한자리에서 볼 수 있다.
        /// </summary>
        [MenuItem("Tools/GameData/Data Generate %g", false, 10)]
        public static void Generate()
        {
            DataPipelinePaths paths = DataPipelineConfig.Load();
            var log = new DataIssueLog();

            ExportResult export = DataExportPipeline.Run(paths, log);

            // 원본을 못 읽었으면 코드 생성까지 가지 않는다. 멀쩡한 코드를 지우게 된다.
            GenerateResult generated = export.TableCount > 0
                ? GenerateCode(export, paths, log)
                : default;

            AssetDatabase.Refresh();

            // 라벨이 없으면 런타임에 JSON 을 한 건도 못 읽는다. 여기서 미리 알려준다.
            if (export.TableCount > 0 && AddressablesSetup.IsRegistered(paths.JsonOutput) == false)
            {
                log.Warning(IssueStage.Generate,
                    $"'{paths.JsonOutput}' 이 Addressables 라벨 '{DataManager.GameDataLabel}' 로 등록되지 않았습니다." +
                    " Tools > GameData > Setup Addressables 를 한 번 실행하세요. 안 하면 런타임에 데이터가 비어 있습니다.");
            }

            Report(export, generated, log);
        }

        private struct GenerateResult
        {
            public bool Ran;
            public int Tables;
            public int Enums;
            public int RootProperties;
        }

        private static GenerateResult GenerateCode(ExportResult export, DataPipelinePaths paths, DataIssueLog log)
        {
            HashSet<string> enumNames = export.Enums != null
                ? export.Enums.NameSet()
                : new HashSet<string>(StringComparer.Ordinal);

            var result = new GenerateResult
            {
                Enums = WriteGameEnum(export.Enums, paths),
                Tables = WriteDataClasses(export.Tables, enumNames, paths, log),
                Ran = true
            };
            WriteContainers(export.Tables, enumNames, paths);
            result.RootProperties = WriteGameRoot(paths, log);
            return result;
        }

        private static void Report(ExportResult export, GenerateResult generated, DataIssueLog log)
        {
            string summary =
                $"[GameData] 원본 {export.FileCount}개 → 표 {export.TableCount}개 / {export.RowCount}행, enum {export.EnumCount}개";

            if (generated.Ran)
            {
                summary += $" · 코드 {generated.Tables}개, 컨테이너 프로퍼티 {generated.RootProperties}개";
            }

            if (log.HasAny == false)
            {
                Debug.Log(summary);
                return;
            }

            string report = summary + chr10 + log.Summary() + chr10 + chr10 + log.BuildReport();
            if (log.HasError)
            {
                Debug.LogError(report);
            }
            else
            {
                Debug.LogWarning(report);
            }
        }

        private const string chr10 = "\n";

        private static int WriteGameEnum(EnumCollector enums, DataPipelinePaths paths)
        {
            if (enums == null || enums.Count == 0)
            {
                return 0;
            }

            IReadOnlyList<string> order = enums.Order;

            var sb = new StringBuilder();
            sb.Append(AutoHeader).AppendLine();
            sb.AppendLine("namespace " + EnumNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public static class " + EnumWrapper);
            sb.AppendLine("    {");

            for (int i = 0; i < order.Count; i++)
            {
                IReadOnlyList<string> members = enums.MembersOf(order[i]);
                sb.AppendLine("        public enum " + order[i]);
                sb.AppendLine("        {");
                for (int m = 0; m < members.Count; m++)
                {
                    sb.Append("            ").Append(members[m]).AppendLine(m < members.Count - 1 ? "," : string.Empty);
                }
                sb.AppendLine("        }");
                if (i < order.Count - 1)
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            WriteIfChanged(DataPipelineConfig.Resolve(paths.GameEnumFile), sb.ToString());
            return order.Count;
        }

        private static int WriteDataClasses(List<ConvertedTable> tables, HashSet<string> enumNames, DataPipelinePaths paths, DataIssueLog log)
        {
            string generatedFolder = DataPipelineConfig.Resolve(paths.GeneratedFolder);
            EnsureFolder(generatedFolder);

            var keep = new HashSet<string>();
            foreach (ConvertedTable table in tables)
            {
                ColumnSpec key = FindKeyColumn(table.Columns);
                string keyType = key != null ? CsType(key.Type, enumNames) : "int";
                string keyProp = key != null ? Pascal(key.Name) : "Id";

                var sb = new StringBuilder();
                sb.Append(AutoHeader);
                sb.AppendLine("using Newtonsoft.Json;");
                sb.AppendLine();
                sb.AppendLine("namespace " + Namespace);
                sb.AppendLine("{");
                sb.AppendLine($"    public partial class {table.Name} : IDataKey<{keyType}>, IData");
                sb.AppendLine("    {");
                sb.AppendLine($"        public const string TableName = \"{table.Name}\";");
                sb.AppendLine();
                foreach (ColumnSpec column in table.Columns)
                {
                    sb.AppendLine($"        [JsonProperty(\"{column.Name}\")] public {CsType(column.Type, enumNames)} {Pascal(column.Name)} {{ get; private set; }}");
                }
                if (keyProp != "Key")
                {
                    sb.AppendLine();
                    sb.AppendLine($"        [JsonIgnore] public {keyType} Key => {keyProp};");
                }
                sb.AppendLine("    }");
                sb.AppendLine("}");

                if (key == null)
                {
                    log.Warning(IssueStage.Generate,
                        $"'{table.Name}' 에 키로 쓸 열이 없어 Id 로 가정합니다.", null, table.Name);
                }

                string path = generatedFolder + "/" + table.Name + ".cs";
                keep.Add(Path.GetFullPath(path));
                WriteIfChanged(path, sb.ToString());
            }

            DeleteStaleGenerated(keep, generatedFolder, paths.GeneratedFolder);
            return tables.Count;
        }

        private static void DeleteStaleGenerated(HashSet<string> keep, string generatedFolder, string generatedRelative)
        {
            foreach (string path in Directory.GetFiles(generatedFolder, "*.cs"))
            {
                if (Path.GetFileName(path) == ContainersFileName)
                {
                    continue;
                }
                if (keep.Contains(Path.GetFullPath(path)))
                {
                    continue;
                }
                string fileName = Path.GetFileName(path);
                if (DataPipelineConfig.IsInsideAssets(generatedRelative))
                {
                    AssetDatabase.DeleteAsset(generatedRelative + "/" + fileName);
                }
                else
                {
                    File.Delete(path);
                }
                Debug.Log($"[GameData] 스키마에 없는 생성 파일 삭제: {fileName}");
            }
        }

        private static void WriteContainers(List<ConvertedTable> tables, HashSet<string> enumNames, DataPipelinePaths paths)
        {
            string generatedFolder = DataPipelineConfig.Resolve(paths.GeneratedFolder);
            EnsureFolder(generatedFolder);

            var sb = new StringBuilder();
            sb.Append(AutoHeader);
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace " + Namespace);
            sb.AppendLine("{");

            bool first = true;
            foreach (ConvertedTable table in tables)
            {
                ColumnSpec key = FindKeyColumn(table.Columns);
                string keyType = key != null ? CsType(key.Type, enumNames) : "int";
                bool hasCode = HasColumn(table.Columns, "code");
                string name = table.Name;

                if (first == false)
                {
                    sb.AppendLine();
                }
                first = false;

                sb.AppendLine($"    public abstract class {name}DictionaryContainer : DictionaryContainer<{keyType}, {name}>");
                sb.AppendLine("    {");
                sb.AppendLine($"        public override string Name => {name}.TableName;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public abstract class {name}DictionaryGroupContainer : DictionaryGroupContainer<{keyType}, {name}>");
                sb.AppendLine("    {");
                sb.AppendLine($"        public override string Name => {name}.TableName;");
                sb.AppendLine("    }");

                if (hasCode && keyType == "int")
                {
                    sb.AppendLine();
                    AppendCodeContainer(sb, name, keyType);
                }
            }

            sb.AppendLine("}");
            WriteIfChanged(generatedFolder + "/" + ContainersFileName, sb.ToString());
        }

        private static void AppendCodeContainer(StringBuilder sb, string name, string keyType)
        {
            sb.AppendLine($"    public abstract class {name}CodeContainer : DictionaryContainer<{keyType}, {name}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string Name => {name}.TableName;");
            sb.AppendLine();
            sb.AppendLine($"        public {name} Get(string code)");
            sb.AppendLine("        {");
            sb.AppendLine($"            IReadOnlyList<{name}> list = GetGroup(code);");
            sb.AppendLine("            return list != null && list.Count > 0 ? list[0] : null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public IReadOnlyList<{name}> GetGroup(string code)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (string.IsNullOrEmpty(code))");
            sb.AppendLine("            {");
            sb.AppendLine("                return null;");
            sb.AppendLine("            }");
            sb.AppendLine($"            _dicByCode.TryGetValue(code, out List<{name}> list);");
            sb.AppendLine("            return list;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public bool TryGet(string code, out {name} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            value = Get(code);");
            sb.AppendLine("            return value != null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public bool ContainsCode(string code)");
            sb.AppendLine("        {");
            sb.AppendLine("            return string.IsNullOrEmpty(code) == false && _dicByCode.ContainsKey(code);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        protected Dictionary<string, List<{name}>> _dicByCode;");
            sb.AppendLine();
            sb.AppendLine("        protected override void SubCollectionConstructor(int count)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.SubCollectionConstructor(count);");
            sb.AppendLine($"            _dicByCode = new Dictionary<string, List<{name}>>(count);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        protected override void SubCollectionAdd({keyType} key, {name} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.SubCollectionAdd(key, value);");
            sb.AppendLine();
            sb.AppendLine("            if (string.IsNullOrEmpty(value.Code))");
            sb.AppendLine("            {");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine($"            if (_dicByCode.TryGetValue(value.Code, out List<{name}> list) == false)");
            sb.AppendLine("            {");
            sb.AppendLine($"                list = new List<{name}>(1);");
            sb.AppendLine("                _dicByCode.Add(value.Code, list);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            list.Add(value);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static int WriteGameRoot(DataPipelinePaths paths, DataIssueLog log)
        {
            string gameRootPath = DataPipelineConfig.Resolve(paths.GameRootFile);
            List<string> names = CollectConcreteContainers(DataPipelineConfig.Resolve(paths.ContainersFolder));
            if (names.Count == 0 && File.Exists(gameRootPath))
            {
                log.Warning(IssueStage.Generate,
                    $"콘크리트 컨테이너가 없어 GameRoot 를 건드리지 않았습니다: {paths.ContainersFolder}");
                return 0;
            }

            var sb = new StringBuilder();
            sb.Append(AutoHeader);
            sb.AppendLine("// 콘크리트 컨테이너(DataLoader/Containers) 추가·삭제 후 다시 실행하면 갱신된다.");
            sb.AppendLine();
            sb.AppendLine("using " + Namespace + ";");
            sb.AppendLine();
            sb.AppendLine("namespace Game_Core");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class GameRoot");
            sb.AppendLine("    {");
            foreach (string name in names)
            {
                sb.AppendLine($"        public {name} {name} => DataManager.Instance.GetContainer<{name}>();");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            WriteIfChanged(gameRootPath, sb.ToString());
            return names.Count;
        }

        private static List<string> CollectConcreteContainers(string containersFolder)
        {
            var names = new List<string>();
            if (Directory.Exists(containersFolder) == false)
            {
                return names;
            }

            var pattern = new Regex(@"public\s+(?:sealed\s+)?class\s+(\w+)\s*:\s*\w*(?:CodeContainer|DictionaryContainer|DictionaryGroupContainer|ListContainer)\b");

            foreach (string path in Directory.GetFiles(containersFolder, "*.cs", SearchOption.AllDirectories))
            {
                foreach (Match match in pattern.Matches(File.ReadAllText(path)))
                {
                    string name = match.Groups[1].Value;
                    if (names.Contains(name) == false)
                    {
                        names.Add(name);
                    }
                }
            }
            names.Sort(StringComparer.Ordinal);
            return names;
        }

        private static ColumnSpec FindKeyColumn(List<ColumnSpec> columns)
        {
            foreach (ColumnSpec c in columns)
            {
                if (string.Equals(c.Name, "id", StringComparison.OrdinalIgnoreCase))
                {
                    return c;
                }
            }
            foreach (ColumnSpec c in columns)
            {
                if (string.Equals(c.Name, "key", StringComparison.OrdinalIgnoreCase))
                {
                    return c;
                }
            }
            return columns.Count > 0 ? columns[0] : null;
        }

        private static bool HasColumn(List<ColumnSpec> columns, string name)
        {
            foreach (ColumnSpec c in columns)
            {
                if (string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }

        private static string CsType(string type, HashSet<string> enumNames)
        {
            string t = string.IsNullOrEmpty(type) ? "string" : type.Trim();
            if (t.EndsWith("!"))
            {
                t = t.Substring(0, t.Length - 1);
            }

            if (enumNames.Contains(t))
            {
                return EnumNamespace + "." + EnumWrapper + "." + t;
            }

            switch (t.ToLowerInvariant())
            {
                case "intarray": return "int[]";
                case "floatarray": return "float[]";
                case "stringarray": return "string[]";
                case "int":
                case "integer": return "int";
                case "long": return "long";
                case "float": return "float";
                case "double": return "double";
                case "number": return "float";
                case "bool":
                case "boolean": return "bool";
                case "string":
                case "text": return "string";
                default:
                    // 알 수 없는 자료형은 변환 단계에서 이미 보고했다. 여기서는 string 으로 둔다.
                    return "string";
            }
        }

        private static string Pascal(string name)
        {
            string s = string.IsNullOrEmpty(name) ? string.Empty : name;
            return s.Length == 0 ? s : char.ToUpperInvariant(s[0]) + s.Substring(1);
        }

        private static string Sanitize(string raw)
        {
            if (string.IsNullOrEmpty(raw))
            {
                return string.Empty;
            }
            var sb = new StringBuilder(raw.Length);
            foreach (char c in raw.Trim())
            {
                bool valid = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_';
                sb.Append(valid ? c : '_');
            }
            if (sb.Length > 0 && sb[0] >= '0' && sb[0] <= '9')
            {
                sb.Insert(0, '_');
            }
            return sb.ToString();
        }

        private static void EnsureFolder(string folder)
        {
            if (Directory.Exists(folder) == false)
            {
                Directory.CreateDirectory(folder);
            }
        }

        private static void WriteIfChanged(string path, string content)
        {
            EnsureFolder(Path.GetDirectoryName(path));
            if (File.Exists(path) && File.ReadAllText(path) == content)
            {
                return;
            }
            File.WriteAllText(path, content);
        }
    }
}
