using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

namespace Game_DataLoader
{
    public static class DbGenerator
    {
        public const string SchemaPath = "Assets/GameDataSchema/_Schema.json";
        public const string DataLoaderFolder = "Assets/Scripts/DataLoader";
        public const string GeneratedFolder = DataLoaderFolder + "/Generated";
        public const string ContainersFolder = DataLoaderFolder + "/Containers";
        public const string GameEnumPath = DataLoaderFolder + "/GameEnum.cs";
        public const string GameRootPath = "Assets/Scripts/Game/Core/GameRoot.Generated.cs";

        public const string ContainersFileName = "Containers.Generated.cs";
        public const string Namespace = "Game_DataLoader";
        public const string EnumNamespace = "Game";
        public const string EnumWrapper = "GameEnum";

        private const string AutoHeader =
            "// <auto-generated />\n" +
            "// Tools > GameData > DB Generate 로 생성된 파일입니다. 수동 편집 금지.\n";

        private sealed class Column
        {
            public string Name;
            public string Type;
        }

        [MenuItem("Tools/GameData/DB Generate %g", false, 10)]
        public static void Generate()
        {
            if (File.Exists(SchemaPath) == false)
            {
                Debug.LogError($"[DbGenerator] 스키마가 없습니다: {SchemaPath}\n_DataExporter/run_win.bat 을 먼저 실행하세요.");
                return;
            }

            JObject root;
            try
            {
                root = JObject.Parse(File.ReadAllText(SchemaPath));
            }
            catch (Exception e)
            {
                Debug.LogError($"[DbGenerator] 스키마 파싱 실패: {e.Message}");
                return;
            }

            Dictionary<string, List<Column>> tables = ReadTables(root);
            List<string> enumOrder = new List<string>();
            Dictionary<string, List<string>> enums = ReadEnums(root, enumOrder);

            int enumCount = WriteGameEnum(enumOrder, enums);
            int tableCount = WriteDataClasses(tables, enums);
            WriteContainers(tables, enums);
            int rootCount = WriteGameRoot();

            AssetDatabase.Refresh();
            Debug.Log($"[DbGenerator] 생성 완료 — 표 {tableCount}개, enum {enumCount}개, 컨테이너 프로퍼티 {rootCount}개");
        }

        [MenuItem("Tools/GameData/스키마 파일 선택", false, 11)]
        private static void PingSchema()
        {
            TextAsset asset = AssetDatabase.LoadAssetAtPath<TextAsset>(SchemaPath);
            if (asset == null)
            {
                Debug.LogWarning($"[DbGenerator] 스키마가 없습니다: {SchemaPath}");
                return;
            }
            EditorGUIUtility.PingObject(asset);
            Selection.activeObject = asset;
        }

        private static Dictionary<string, List<Column>> ReadTables(JObject root)
        {
            var result = new Dictionary<string, List<Column>>();
            if ((root["tables"] is JObject tables) == false)
            {
                return result;
            }

            foreach (JProperty table in tables.Properties())
            {
                var columns = new List<Column>();
                if (table.Value is JArray array)
                {
                    foreach (JToken token in array)
                    {
                        if ((token is JObject column) == false)
                        {
                            continue;
                        }
                        string name = (string)column["name"];
                        string type = (string)column["type"];
                        if (string.IsNullOrEmpty(name))
                        {
                            continue;
                        }
                        columns.Add(new Column { Name = name, Type = string.IsNullOrEmpty(type) ? "string" : type });
                    }
                }
                if (columns.Count > 0)
                {
                    result[table.Name] = columns;
                }
            }
            return result;
        }

        private static Dictionary<string, List<string>> ReadEnums(JObject root, List<string> order)
        {
            var result = new Dictionary<string, List<string>>();
            if ((root["enums"] is JObject enums) == false)
            {
                return result;
            }

            foreach (JProperty item in enums.Properties())
            {
                var members = new List<string>();
                var seen = new HashSet<string>();
                if (item.Value is JArray array)
                {
                    foreach (JToken token in array)
                    {
                        string member = Sanitize(token.ToString());
                        if (member.Length == 0 || seen.Add(member) == false)
                        {
                            continue;
                        }
                        members.Add(member);
                    }
                }
                if (members.Count > 0)
                {
                    result[item.Name] = members;
                    order.Add(item.Name);
                }
            }
            return result;
        }

        private static int WriteGameEnum(List<string> order, Dictionary<string, List<string>> enums)
        {
            if (order.Count == 0)
            {
                return 0;
            }

            var sb = new StringBuilder();
            sb.Append(AutoHeader).AppendLine();
            sb.AppendLine("namespace " + EnumNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public static class " + EnumWrapper);
            sb.AppendLine("    {");

            for (int i = 0; i < order.Count; i++)
            {
                List<string> members = enums[order[i]];
                sb.AppendLine("        public enum " + order[i]);
                sb.AppendLine("        {");
                for (int m = 0; m < members.Count; m++)
                {
                    sb.Append("            ").Append(members[m]).AppendLine(m < members.Count - 1 ? "," : string.Empty);
                }
                sb.AppendLine("        }");
                if (i < order.Count - 1)
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            WriteIfChanged(GameEnumPath, sb.ToString());
            return order.Count;
        }

        private static int WriteDataClasses(Dictionary<string, List<Column>> tables, Dictionary<string, List<string>> enums)
        {
            EnsureFolder(GeneratedFolder);

            var keep = new HashSet<string>();
            foreach (KeyValuePair<string, List<Column>> table in tables)
            {
                Column key = FindKeyColumn(table.Value);
                string keyType = key != null ? CsType(key.Type, enums) : "int";
                string keyProp = key != null ? Pascal(key.Name) : "Id";

                var sb = new StringBuilder();
                sb.Append(AutoHeader);
                sb.AppendLine("using Newtonsoft.Json;");
                sb.AppendLine();
                sb.AppendLine("namespace " + Namespace);
                sb.AppendLine("{");
                sb.AppendLine($"    public partial class {table.Key} : IDataKey<{keyType}>, IData");
                sb.AppendLine("    {");
                sb.AppendLine($"        public const string TableName = \"{table.Key}\";");
                sb.AppendLine();
                foreach (Column column in table.Value)
                {
                    sb.AppendLine($"        [JsonProperty(\"{column.Name}\")] public {CsType(column.Type, enums)} {Pascal(column.Name)} {{ get; private set; }}");
                }
                if (keyProp != "Key")
                {
                    sb.AppendLine();
                    sb.AppendLine($"        [JsonIgnore] public {keyType} Key => {keyProp};");
                }
                sb.AppendLine("    }");
                sb.AppendLine("}");

                string path = GeneratedFolder + "/" + table.Key + ".cs";
                keep.Add(Path.GetFullPath(path));
                WriteIfChanged(path, sb.ToString());
            }

            DeleteStaleGenerated(keep);
            return tables.Count;
        }

        private static void DeleteStaleGenerated(HashSet<string> keep)
        {
            foreach (string path in Directory.GetFiles(GeneratedFolder, "*.cs"))
            {
                if (Path.GetFileName(path) == ContainersFileName)
                {
                    continue;
                }
                if (keep.Contains(Path.GetFullPath(path)))
                {
                    continue;
                }
                AssetDatabase.DeleteAsset(path.Replace('\\', '/'));
                Debug.Log($"[DbGenerator] 스키마에 없는 생성 파일 삭제: {Path.GetFileName(path)}");
            }
        }

        private static void WriteContainers(Dictionary<string, List<Column>> tables, Dictionary<string, List<string>> enums)
        {
            EnsureFolder(GeneratedFolder);

            var sb = new StringBuilder();
            sb.Append(AutoHeader);
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace " + Namespace);
            sb.AppendLine("{");

            bool first = true;
            foreach (KeyValuePair<string, List<Column>> table in tables)
            {
                Column key = FindKeyColumn(table.Value);
                string keyType = key != null ? CsType(key.Type, enums) : "int";
                bool hasCode = HasColumn(table.Value, "code");
                string name = table.Key;

                if (first == false)
                {
                    sb.AppendLine();
                }
                first = false;

                sb.AppendLine($"    public abstract class {name}DictionaryContainer : DictionaryContainer<{keyType}, {name}>");
                sb.AppendLine("    {");
                sb.AppendLine($"        public override string Name => {name}.TableName;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public abstract class {name}DictionaryGroupContainer : DictionaryGroupContainer<{keyType}, {name}>");
                sb.AppendLine("    {");
                sb.AppendLine($"        public override string Name => {name}.TableName;");
                sb.AppendLine("    }");

                if (hasCode && keyType == "int")
                {
                    sb.AppendLine();
                    AppendCodeContainer(sb, name, keyType);
                }
            }

            sb.AppendLine("}");
            WriteIfChanged(GeneratedFolder + "/" + ContainersFileName, sb.ToString());
        }

        private static void AppendCodeContainer(StringBuilder sb, string name, string keyType)
        {
            sb.AppendLine($"    public abstract class {name}CodeContainer : DictionaryContainer<{keyType}, {name}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string Name => {name}.TableName;");
            sb.AppendLine();
            sb.AppendLine($"        public {name} Get(string code)");
            sb.AppendLine("        {");
            sb.AppendLine($"            IReadOnlyList<{name}> list = GetGroup(code);");
            sb.AppendLine("            return list != null && list.Count > 0 ? list[0] : null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public IReadOnlyList<{name}> GetGroup(string code)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (string.IsNullOrEmpty(code))");
            sb.AppendLine("            {");
            sb.AppendLine("                return null;");
            sb.AppendLine("            }");
            sb.AppendLine($"            _dicByCode.TryGetValue(code, out List<{name}> list);");
            sb.AppendLine("            return list;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public bool TryGet(string code, out {name} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            value = Get(code);");
            sb.AppendLine("            return value != null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public bool ContainsCode(string code)");
            sb.AppendLine("        {");
            sb.AppendLine("            return string.IsNullOrEmpty(code) == false && _dicByCode.ContainsKey(code);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        protected Dictionary<string, List<{name}>> _dicByCode;");
            sb.AppendLine();
            sb.AppendLine("        protected override void SubCollectionConstructor(int count)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.SubCollectionConstructor(count);");
            sb.AppendLine($"            _dicByCode = new Dictionary<string, List<{name}>>(count);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        protected override void SubCollectionAdd({keyType} key, {name} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.SubCollectionAdd(key, value);");
            sb.AppendLine();
            sb.AppendLine("            if (string.IsNullOrEmpty(value.Code))");
            sb.AppendLine("            {");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine($"            if (_dicByCode.TryGetValue(value.Code, out List<{name}> list) == false)");
            sb.AppendLine("            {");
            sb.AppendLine($"                list = new List<{name}>(1);");
            sb.AppendLine("                _dicByCode.Add(value.Code, list);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            list.Add(value);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static int WriteGameRoot()
        {
            List<string> names = CollectConcreteContainers();
            if (names.Count == 0 && File.Exists(GameRootPath))
            {
                Debug.LogWarning($"[DbGenerator] 콘크리트 컨테이너가 없어 GameRoot 생성을 건너뜁니다: {ContainersFolder}");
                return 0;
            }

            var sb = new StringBuilder();
            sb.Append(AutoHeader);
            sb.AppendLine("// 콘크리트 컨테이너(DataLoader/Containers) 추가·삭제 후 다시 실행하면 갱신된다.");
            sb.AppendLine();
            sb.AppendLine("using " + Namespace + ";");
            sb.AppendLine();
            sb.AppendLine("namespace Game_Core");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class GameRoot");
            sb.AppendLine("    {");
            foreach (string name in names)
            {
                sb.AppendLine($"        public {name} {name} => DataManager.Instance.GetContainer<{name}>();");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            WriteIfChanged(GameRootPath, sb.ToString());
            return names.Count;
        }

        private static List<string> CollectConcreteContainers()
        {
            var names = new List<string>();
            if (Directory.Exists(ContainersFolder) == false)
            {
                return names;
            }

            var pattern = new Regex(@"public\s+(?:sealed\s+)?class\s+(\w+)\s*:\s*\w*(?:CodeContainer|DictionaryContainer|DictionaryGroupContainer|ListContainer)\b");

            foreach (string path in Directory.GetFiles(ContainersFolder, "*.cs", SearchOption.AllDirectories))
            {
                foreach (Match match in pattern.Matches(File.ReadAllText(path)))
                {
                    string name = match.Groups[1].Value;
                    if (names.Contains(name) == false)
                    {
                        names.Add(name);
                    }
                }
            }
            names.Sort(StringComparer.Ordinal);
            return names;
        }

        private static Column FindKeyColumn(List<Column> columns)
        {
            foreach (Column c in columns)
            {
                if (string.Equals(c.Name, "id", StringComparison.OrdinalIgnoreCase))
                {
                    return c;
                }
            }
            foreach (Column c in columns)
            {
                if (string.Equals(c.Name, "key", StringComparison.OrdinalIgnoreCase))
                {
                    return c;
                }
            }
            return columns.Count > 0 ? columns[0] : null;
        }

        private static bool HasColumn(List<Column> columns, string name)
        {
            foreach (Column c in columns)
            {
                if (string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }

        private static string CsType(string type, Dictionary<string, List<string>> enums)
        {
            string t = string.IsNullOrEmpty(type) ? "string" : type.Trim();
            if (t.EndsWith("!"))
            {
                t = t.Substring(0, t.Length - 1);
            }

            if (enums.ContainsKey(t))
            {
                return EnumNamespace + "." + EnumWrapper + "." + t;
            }

            switch (t.ToLowerInvariant())
            {
                case "intarray": return "int[]";
                case "floatarray": return "float[]";
                case "stringarray": return "string[]";
                case "int":
                case "integer": return "int";
                case "long": return "long";
                case "float": return "float";
                case "double": return "double";
                case "number": return "float";
                case "bool":
                case "boolean": return "bool";
                case "string":
                case "text": return "string";
                default:
                    if (t.Length > 0 && char.IsUpper(t[0]))
                    {
                        Debug.LogWarning($"[DbGenerator] 알 수 없는 자료형 '{t}' — enum이라면 _Enum 정의에 추가하세요. string으로 처리합니다.");
                    }
                    return "string";
            }
        }

        private static string Pascal(string name)
        {
            string s = string.IsNullOrEmpty(name) ? string.Empty : name;
            return s.Length == 0 ? s : char.ToUpperInvariant(s[0]) + s.Substring(1);
        }

        private static string Sanitize(string raw)
        {
            if (string.IsNullOrEmpty(raw))
            {
                return string.Empty;
            }
            var sb = new StringBuilder(raw.Length);
            foreach (char c in raw.Trim())
            {
                bool valid = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_';
                sb.Append(valid ? c : '_');
            }
            if (sb.Length > 0 && sb[0] >= '0' && sb[0] <= '9')
            {
                sb.Insert(0, '_');
            }
            return sb.ToString();
        }

        private static void EnsureFolder(string folder)
        {
            if (Directory.Exists(folder) == false)
            {
                Directory.CreateDirectory(folder);
            }
        }

        private static void WriteIfChanged(string path, string content)
        {
            EnsureFolder(Path.GetDirectoryName(path));
            if (File.Exists(path) && File.ReadAllText(path) == content)
            {
                return;
            }
            File.WriteAllText(path, content);
        }
    }
}
