using System.Collections.Generic;
using System.IO;
using System.Text;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

namespace Game_DataLoader
{
    /// <summary>
    /// enum 정의용 JSON(기본 파일명 패턴 "_Enum")을 읽어
    /// GameEnum 클래스 안에 중첩 enum으로 생성한다.
    ///  - 행     = enum 멤버 하나
    ///  - "Enum"  컬럼 = enum 이름
    ///  - "Value" 컬럼 = 멤버 이름
    /// 값(정수)은 등장 순서대로 자동 배정(0,1,2...), 중복 멤버/`#` 시작은 스킵.
    /// </summary>
    public static class GameEnumGenerator
    {
        public const string JsonFolder = "Assets/GameData";
        public const string OutputFolder = "Assets/Scripts/DataLoader";
        public const string OutputFileName = "GameEnum.cs";
        public const string EnumNamespace = "Game";
        public const string WrapperClass = "GameEnum";

        public const string EnumColumn = "Enum";
        public const string ValueColumn = "Value";

        public const string PrefKeyPatterns = "GameEnumGenerator.Patterns";
        public const string DefaultPatterns = "_Enum";

        public static string Generate(string patternsCsv, out int enumCount, out int memberCount)
        {
            enumCount = 0;
            memberCount = 0;

            List<string> patterns = SplitPatterns(patternsCsv);
            if (patterns.Count == 0)
            {
                patterns.Add(DefaultPatterns);
            }

            var order = new List<string>();
            var members = new Dictionary<string, List<string>>();
            var seen = new Dictionary<string, HashSet<string>>();

            if (Directory.Exists(JsonFolder) == false)
            {
                Debug.LogWarning($"[GameEnumGenerator] 폴더가 없습니다: {JsonFolder}");
                return null;
            }

            foreach (string path in Directory.GetFiles(JsonFolder, "*.json"))
            {
                string fileName = Path.GetFileNameWithoutExtension(path);
                if (MatchesAny(fileName, patterns) == false)
                {
                    continue;
                }
                CollectFromFile(path, order, members, seen);
            }

            if (order.Count == 0)
            {
                Debug.LogWarning("[GameEnumGenerator] 생성할 enum이 없습니다. (파일명 패턴 / Enum·Value 컬럼 확인)");
                return null;
            }

            EnsureFolder(OutputFolder);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// GameEnumGenerator로 자동 생성된 파일입니다. 수동 편집 금지.");
            sb.AppendLine();
            sb.AppendLine("namespace " + EnumNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public static class " + WrapperClass);
            sb.AppendLine("    {");

            for (int i = 0; i < order.Count; i++)
            {
                string name = order[i];
                List<string> vals = members[name];

                sb.AppendLine("        public enum " + name);
                sb.AppendLine("        {");
                for (int v = 0; v < vals.Count; v++)
                {
                    sb.Append("            ").Append(vals[v]);
                    sb.AppendLine(v < vals.Count - 1 ? "," : string.Empty);
                }
                sb.AppendLine("        }");
                if (i < order.Count - 1)
                {
                    sb.AppendLine();
                }

                enumCount++;
                memberCount += vals.Count;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string outPath = Path.Combine(OutputFolder, OutputFileName).Replace('\\', '/');
            File.WriteAllText(outPath, sb.ToString());
            return outPath;
        }

        private static void CollectFromFile(string path, List<string> order,
            Dictionary<string, List<string>> members, Dictionary<string, HashSet<string>> seen)
        {
            JArray arr;
            try
            {
                arr = JArray.Parse(File.ReadAllText(path));
            }
            catch (System.Exception e)
            {
                Debug.LogWarning($"[GameEnumGenerator] '{Path.GetFileName(path)}' 파싱 실패: {e.Message}");
                return;
            }

            foreach (JToken token in arr)
            {
                if ((token is JObject obj) == false)
                {
                    continue;
                }

                string rawEnumName = SanitizeIdentifier(GetString(obj, EnumColumn));
                string memberRaw = GetString(obj, ValueColumn);

                if (string.IsNullOrEmpty(rawEnumName) || rawEnumName == "_")
                {
                    continue;
                }

                string enumName = NormalizeEnumName(rawEnumName);
                if (enumName != rawEnumName)
                {
                    Debug.LogWarning($"[GameEnumGenerator] enum 이름 컨벤션 위반: '{rawEnumName}' -> '{enumName}' 로 정규화됨. 원본 데이터를 수정하세요.");
                }
                if (string.IsNullOrEmpty(memberRaw) || memberRaw.StartsWith("#"))
                {
                    continue;
                }

                string member = SanitizeIdentifier(memberRaw);

                if (members.TryGetValue(enumName, out List<string> list) == false)
                {
                    list = new List<string>();
                    members[enumName] = list;
                    seen[enumName] = new HashSet<string>();
                    order.Add(enumName);
                }

                if (seen[enumName].Add(member) == false)
                {
                    continue;
                }
                list.Add(member);
            }
        }

        private static string GetString(JObject obj, string key)
        {
            JToken t = obj[key];
            if (t == null || t.Type == JTokenType.Null)
            {
                return null;
            }
            return t.ToString().Trim();
        }

        private static List<string> SplitPatterns(string csv)
        {
            var list = new List<string>();
            if (string.IsNullOrEmpty(csv))
            {
                return list;
            }
            foreach (string raw in csv.Split(','))
            {
                string t = raw.Trim();
                if (t.Length > 0)
                {
                    list.Add(t);
                }
            }
            return list;
        }

        private static bool MatchesAny(string fileName, List<string> patterns)
        {
            for (int i = 0; i < patterns.Count; i++)
            {
                if (fileName.IndexOf(patterns[i], System.StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return true;
                }
            }
            return false;
        }

        private static void EnsureFolder(string folder)
        {
            if (Directory.Exists(folder) == false)
            {
                Directory.CreateDirectory(folder);
            }
        }

        /// <summary>
        /// enum 네이밍 컨벤션 강제: E접두사 제거 + 'Type' 접미사 필수
        /// (예: EStatType -> StatType, ECurrency -> CurrencyType)
        /// </summary>
        private static string NormalizeEnumName(string name)
        {
            string n = name;
            if (n.Length >= 2 && n[0] == 'E' && char.IsUpper(n[1]))
            {
                n = n.Substring(1);
            }
            if (n.EndsWith("Type") == false)
            {
                n += "Type";
            }
            return n;
        }

        private static string SanitizeIdentifier(string raw)
        {
            if (string.IsNullOrEmpty(raw))
            {
                return "_";
            }
            var sb = new StringBuilder(raw.Length);
            for (int i = 0; i < raw.Length; i++)
            {
                char c = raw[i];
                bool valid = (c >= 'a' && c <= 'z')
                             || (c >= 'A' && c <= 'Z')
                             || (c >= '0' && c <= '9')
                             || c == '_';
                sb.Append(valid ? c : '_');
            }
            if (sb.Length > 0 && sb[0] >= '0' && sb[0] <= '9')
            {
                sb.Insert(0, '_');
            }
            return sb.ToString();
        }
    }

    public class GameEnumGeneratorWindow : EditorWindow
    {
        private string _patterns;

        [MenuItem("Tools/GameData/GameEnum Generator")]
        private static void Open()
        {
            GetWindow<GameEnumGeneratorWindow>("GameEnum Generator");
        }

        private void OnEnable()
        {
            _patterns = EditorPrefs.GetString(GameEnumGenerator.PrefKeyPatterns, GameEnumGenerator.DefaultPatterns);
        }

        private void OnGUI()
        {
            EditorGUILayout.LabelField("GameEnum 생성", EditorStyles.boldLabel);
            EditorGUILayout.HelpBox(
                "enum 정의 JSON을 읽어 GameEnum 클래스(중첩 enum)를 생성합니다.\n" +
                "행 = enum 멤버,  \"Enum\" 컬럼 = enum 이름,  \"Value\" 컬럼 = 멤버 이름.\n" +
                "파일 인식: 파일명에 아래 패턴이 포함되면 대상 (콤마 구분, 대소문자 무시).",
                MessageType.Info);

            _patterns = EditorGUILayout.TextField("파일명 패턴", _patterns);

            EditorGUILayout.Space();
            if (GUILayout.Button("Generate GameEnum"))
            {
                EditorPrefs.SetString(GameEnumGenerator.PrefKeyPatterns, _patterns);
                Run(_patterns);
            }
        }

        private static void Run(string patterns)
        {
            string path = GameEnumGenerator.Generate(patterns, out int enumCount, out int memberCount);
            AssetDatabase.Refresh();
            if (string.IsNullOrEmpty(path))
            {
                return;
            }
            Debug.Log($"[GameEnumGenerator] 생성 완료: {path} (enum {enumCount}개, 멤버 {memberCount}개)");
        }
    }
}
